const mainText = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sodales nibh elit, eget finibus leo pellentesque quis. Duis vestibulum quis quam a ultrices. Suspendisse in pulvinar nisi, non dictum justo. Vivamus faucibus magna mauris, a hendrerit felis vestibulum a. Etiam lobortis purus eget nisi ultricies, non tincidunt orci suscipit. Ut at venenatis turpis. Aliquam erat volutpat. Maecenas pellentesque facilisis velit et sodales. Maecenas ut orci eget leo feugiat pharetra maximus non orci. Nunc egestas elit eu sem laoreet venenatis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed rutrum magna mauris, at ultrices quam ornare eu. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Proin nisl est, molestie vitae tincidunt id, maximus vestibulum erat. Etiam vel ante ac nibh pulvinar venenatis ut eget sapien. Etiam blandit rhoncus metus et venenatis. Etiam tristique, nulla in vestibulum lacinia, massa tortor gravida lorem, at facilisis justo magna ut mauris. Ut ac tincidunt neque. Nunc rhoncus facilisis nulla et dapibus. Nunc tristique, nisi quis viverra rhoncus, sapien dui sollicitudin ligula, eu consectetur metus mauris non enim. Quisque rutrum magna vestibulum felis rutrum, in placerat sapien blandit. Nulla iaculis blandit vehicula.

Etiam pulvinar nec eros eget pellentesque. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam tincidunt gravida dolor sed facilisis. Curabitur finibus neque non neque faucibus, ac hendrerit ligula molestie. Mauris bibendum ante vitae eros accumsan, at finibus mauris accumsan. Fusce placerat lobortis faucibus. Sed id urna vel tortor ornare euismod. Nunc luctus ex commodo turpis convallis, dictum congue urna auctor. Vivamus lacinia sodales sapien, posuere mattis libero. Proin eget tristique mauris, ut ullamcorper quam. Sed consequat magna tortor. Duis ac quam volutpat, maximus diam in, sagittis libero. Cras faucibus orci finibus justo lobortis, in euismod dui volutpat. Pellentesque elementum luctus nulla, et molestie ligula lacinia a. Donec molestie lacinia lacinia.

Integer placerat est eget nibh vulputate blandit. Pellentesque condimentum volutpat viverra. Integer vel consequat massa, non consequat elit. Nunc ullamcorper interdum ex ut efficitur. Mauris eget lacus eget nunc maximus vulputate. Nam iaculis tellus eget pulvinar cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis porta tincidunt ante vitae vestibulum. Etiam vitae hendrerit purus, et placerat velit. Maecenas non posuere mauris.

Proin est sem, facilisis a placerat eu, ornare vel metus. Suspendisse suscipit lacinia lorem eu rutrum. Etiam finibus tellus vel risus venenatis fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin facilisis ex massa, viverra ullamcorper erat volutpat laoreet. Ut sollicitudin neque sed purus pellentesque, sed posuere nibh feugiat. Donec vestibulum leo non ultrices convallis. Nulla id dolor quis dui sagittis interdum. Duis consectetur elit ut augue ultricies, et varius diam pellentesque.

Nulla nec consectetur lectus, sed accumsan odio. Nulla commodo lobortis semper. Duis in vulputate nisi, vel iaculis arcu. Vestibulum porta nulla elit. Donec tempor nibh vel odio sollicitudin bibendum. Integer faucibus euismod faucibus. Mauris sollicitudin non risus vel faucibus. Suspendisse sed dui felis. Aliquam erat volutpat. Aenean faucibus sapien in dui varius, eget gravida leo maximus. Proin justo quam, tempor finibus posuere ut, lacinia eu erat. Pellentesque risus ipsum, imperdiet ac lacus vitae, consequat malesuada metus. Ut varius egestas mauris, ut rhoncus ex commodo eget. Suspendisse fermentum arcu sed est rhoncus auctor. Sed at enim vel lorem rhoncus fermentum ac ac nibh. Vivamus vestibulum tortor at ipsum fringilla pharetra.''';